version: '3.8'
services:
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8081
  stock-service:
    build:
      context: ./stock-service
    container_name: stock-service
    ports:
      - "8082:8082"
    depends_on:
      - user-service
    environment:
      - USER_SERVICE_URL=http://user-service:8080
  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "8083:8083"
    depends_on:
      - user-service
      - stock-service
    environment:
      - USER_SERVICE_URL=http://user-service:8080
      - STOCK_SERVICE_URL=http://stock-service:8082